export const HOTELS_LIST_REQUEST = "HOTELS_LIST_REQUEST";
export const HOTELS_LIST_SUCCESS = "HOTELS_LIST_SUCCESS";
export const HOTELS_LIST_FAILURE = "HOTELS_LIST_FAILURE";
export const HOTELS_LIST_OPTIONS = "HOTELS_LIST_OPTIONS";
