export const HOTEL_LIST_REQUEST = "HOTEL_LIST_REQUEST";
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS";
export const HOTEL_LIST_FAILURE = "HOTEL_LIST_FAILURE";
export const HOTEL_LIST_OPTIONS = "HOTEL_LIST_OPTIONS";
